# appdata/config/style_constants.py
ACCENT_COLOR = "#4F9F68"
BACKGROUND_MAIN = "#272727"
TEXT_COLOR = "#EDEDED"
GROUP_HOVER = "#404040"
GROUP_DEFAULT = "#2E2E2E"
INSTANCE_DEFAULT = "#1F1F1F"
FONT_FAMILY = "Segoe UI"
FONT_SIZE = 10
