# appdata/config/style_constants.py
"""
Shared visual constants for Instanciar.

This maps the requested palette into a dark, user-first dashboard theme.
"""

# Section Name | Requested palette
PALETTE_CHARCOAL = "#3E4642"
PALETTE_GREEN = "#4D6A5A"
PALETTE_ORANGE = "#D37945"
PALETTE_MIST = "#DDE3E0"
PALETTE_WHITE = "#F5F6F3"

# Section Name | Dark dashboard surfaces derived from the palette
APP_BACKGROUND = "#0E1412"
BACKGROUND_MAIN = APP_BACKGROUND
SIDEBAR_BACKGROUND = "#121A17"
CARD_BACKGROUND = "#18221E"
CARD_BACKGROUND_LIGHT = "#202C27"
SURFACE_COLOR = "#26342F"
SURFACE_SOFT = "#1D2824"
GROUP_HOVER = "#293A33"
GROUP_DEFAULT = "#1E2A25"
INSTANCE_DEFAULT = "#111814"

# Section Name | Text and borders
TEXT_COLOR = PALETTE_WHITE
MUTED_TEXT_COLOR = PALETTE_MIST
SUBTLE_TEXT_COLOR = "#9EB0A7"
BORDER_COLOR = "#33473F"
BORDER_COLOR_STRONG = PALETTE_GREEN
FOCUS_COLOR = "#86A895"

# Section Name | Actions and states
ACCENT_COLOR = PALETTE_GREEN
ACCENT_COLOR_HOVER = "#5E806D"
WARNING_COLOR = PALETTE_ORANGE
WARNING_COLOR_HOVER = "#EA8B4E"
SUCCESS_COLOR = "#73C28A"
DANGER_COLOR = "#E36B5C"
DANGER_COLOR_HOVER = "#F17768"
BUTTON_TEXT_LIGHT = PALETTE_WHITE

# Section Name | Proxy/status colors
PROXY_OK_COLOR = SUCCESS_COLOR
PROXY_FAIL_COLOR = "#FF6B6B"
PROXY_DEFAULT_COLOR = PALETTE_ORANGE

FONT_FAMILY = "Segoe UI"
FONT_SIZE = 10
